name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: ['8.3.9', '8.3.9']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install Fileinfo Extension (for Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get install php8.3-fileinfo

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Dump Autoload
        run: composer dump-autoload

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Create SQLite Database
        run: |
          touch database/database.sqlite
          chmod 777 database/database.sqlite

      - name: Run Migrations
        run: php artisan migrate --env=testing

      - name: Run Linter (Pint)
        run: vendor/bin/pint --test

      - name: Run Tests
        run: php artisan test
