name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: ['8.1', '8.2']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Dump Autoload
        run: composer dump-autoload

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Linter (Pint)
        run: vendor/bin/pint --test

      - name: Run Tests
        run: php artisan test
